[workspace]
members = ["mlua-extras"]

[package]
name = "lua_scripted_game"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua-extras = { features = [
    "derive",
    "lua54",
    "serialize",
], path = "./mlua-extras/" }

serde = "1.0.216"
